package autogenerated_sim;

import sim.util.Double2D;

public class Tracking_Stats {
	public double timeTracked;
	public double trackLength;
	public double trackLengthScaled;
	public double trackedVelocity;
	public Double2D agentTrackStartLocation;
	public Double2D agentTrackEndLocation;
	public Double2D agentPreviousLocation;
}
	

